version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python3 /app/run.py