# Generated by Django 4.2.4 on 2023-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prepod',
        ),
        migrations.AddField(
            model_name='submission',
            name='student_uid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='prepod_uid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
